config/routes.rb
Rails.application.routes.draw do
root "doctors#index"

resources :doctors do
  resources :appointments
end

resources :patients

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ApplicationRecord
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :doctors, through: :appointments

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_doctor

  def index
    @appointments = @doctor.appointments
  end

  def new
    @patients = Patient.all
    @appointment = @doctor.appointments.new
    render "form"
  end

  def create
    @appointment = @doctor.appointments.create(appointment_params)
    if @appointment.save
      redirect_to doctor_appointments_path(@doctor)    
    else
      render :new
    end
  end

  # def edit
  # end

  # def update
  # end

  def show
  end

  def destroy
    @appointment = @doctor.appointments.find(params[:id])
    @appointment.destroy
    redirect_to doctor_appointments_path(@doctor)
  end

  private

    def set_doctor
      @doctor = Doctor.find(params[:doctor_id])
    end

    def appointment_params
      params.require(:appointment).permit(:dateTime, :location, :patient_id)
    end

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  def index
    @doctors = Doctor.all.sort_by { |n| n.first_name }
  end

  def show
  end

  def new
    @doctor = Doctor.new
    render "form"
  end

  def create
    @doctor = Doctor.create(doctor_params)
    if @doctor.save
      redirect_to doctors_path
    else
      render :new
    end
  end

  def edit
    render "form"
  end

  def update
    if @doctor.update(doctor_params)
      redirect_to doctor_path(@doctor)
    else
      render :edit
    end
  end

  def destroy
    @doctor = Doctor.find(params[:id])
    @doctor.destroy
    redirect_to doctors_path
  end

  private
    def doctor_params
      params.require(:doctor).permit(:first_name, :last_name, :specialty, :age)
    end
 
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  def index
    @patients = Patient.all.sort_by { |n| n.first_name }
  end

  def show
  end

  def new
    @patient = Patient.new
    render "form"
  end

  def create
    @patient = Patient.create(patient_params)
    if @patient.save
      redirect_to patients_path
    else
      render :new
    end
  end

  def edit
    render "form"
  end

  def update
    if @patient.update(patient_params)
      redirect_to patients_path
    else
      render :edit
    end
  end

  def destroy
    @patient.destroy
    redirect_to patients_path
  end

  private
    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :age, :gender)
    end
 
    def set_patient
      @patient = Patient.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/form.html.erb
<h1><%= @appointment.dateTime ? "Edit " : "New " %>Appointment with Dr. <%= @doctor.full_name %></h1>
<%= form_with(model: [@doctor, @appointment], local: true, class: "ui form") do |f| %>
<div class="form_input_label"><%= f.label :dateTime, "Date & Time" %></div>
<div class="form_input"><%= f.text_field :dateTime %></div>
<div class="form_input_label"><%= f.label :location %></div>
<div class="form_input"><%= f.select :location, ["Office #1", "Office #2", "Office #3"] %></div>
<div class="form_input_label"><%= f.label :patient_id, "Patient Name" %></div>
<div class="form_input"><%= f.select :patient_id, @patients.collect { |patient| [patient.full_name, patient.id] } %></div>
<%= f.submit %>
<% end %>
<br />
<hr />

app/views/appointments/index.html.erb
<h1>Appointments for Dr. <%= @doctor.full_name %></h1>
<%= button_to "New Appointment", new_doctor_appointment_path(@doctor), method: :get %>
<br />
<hr />
<% @appointments.each do |appointment| %>
<div>
  <div>Patient: <%= appointment.patient.full_name %></div>
  <div>Date/Time: <%= appointment.dateTime %></div>
  <div>Location: <%= appointment.location %></div>
  <div><%= button_to "Cancel Appointment", doctor_appointment_path(@doctor, appointment), method: :delete %></div>
</div>
<br />
<% end %>
<hr />

app/views/doctors/form.html.erb
<h1><%= @doctor.first_name ? "Edit " : "New " %>Doctor</h1>
<div class="form_input"><%= form_with(model: @doctor, local: true) do |f| %><?div>
<div class="form_input_label"><%= f.label :first_name %></div>
<div class="form_input"><%= f.text_field :first_name %></div>
<div class="form_input_label"><%= f.label :last_name %></div>
<div class="form_input"><%= f.text_field :last_name %></div>
<div class="form_input_label"><%= f.label :specialty %></div>
<div class="form_input"><%= f.text_field :specialty %></div>
<div class="form_input_label"><%= f.label :age %></div>
<div class="form_input"><%= f.number_field :age %></div>
<div class="form_input"><%= f.submit %></div>
<% end %>
</hr>

app/views/doctors/index.html.erb
<h1>Doctors</h1>
<hr />
<div>
  <% @doctors.each do |doctor| %>
    <div>
    <%= link_to doctor.full_name, doctor_path(doctor) %>
    </div>
  <% end %>
</div>
<hr />

app/views/doctors/show.html.erb
<h1>Dr. <%=@doctor.full_name%></h1>
<h3>Specialty in: <%= @doctor.specialty %>
<h3>Age: <%= @doctor.age %>
<h3>Contact Information: </h3>
<h4>
<div><%= button_to "Edit Doctor", edit_doctor_path(@doctor), method: :get %></div>
<br />
<div><%= button_to "Delete Doctor", doctor_path(@doctor), method: :delete %></div>
</h4>
<hr />
<h4><%= link_to "Appointments for Dr. #{@doctor.full_name}", doctor_appointments_path(@doctor), method: :get, class: "links" %>
</h4>

app/views/layouts/_navbar.html.erb
<div>
<div class="container">
<a><%= link_to 'Doctors', doctors_path, class: "nav-item" %></a>
<a><%= link_to 'New Doctor', new_doctor_path, class: "nav-item" %></a>
<a><%= link_to 'Patients', patients_path, class: "nav-item"  %></a>
<a><%= link_to 'New Patient', new_patient_path, class: "nav-item"  %></a>
<a class="nav-item-empty"></a>
<a class="nav-item-empty"></a>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Doctors</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
    <%= render "layouts/navbar" %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/patients/form.html.erb
<h1><%= @patient.first_name ? "Edit " : "New " %>Patient</h1>
<div>
<div class="form_input"><%= form_with(model: @patient, local: true, class: "ui-form") do |f| %></div>
<div class="form_input_label"><%= f.label :first_name %></div>
<div class="form_input"><%= f.text_field :first_name %></div>
<div class="form_input_label"><%= f.label :last_name %></div>
<div class="form_input"><%= f.text_field :last_name %></div>
<div class="form_input_label"><%= f.label :age %></div>
<div class="form_input"><%= f.number_field :age %></div>
<div class="form_input_label"><%= f.label :gender, "Chromosomes: " %>
<span class="custom_select"><%= f.select :gender, ["XX", "XY"], class: "select" %></span></div>
<br />
<div class="form_input"><%= f.submit %></div>
<div class="form_input"><% end %>
</div>
<hr />

app/views/patients/index.html.erb
<h1>Patients</h1>
<hr />
<div>
  <% @patients.each do |patient| %>
    <div>
    <%= link_to patient.full_name, patient_path(patient) %>
    </div>
  <% end %>
</div>
<hr />

app/views/patients/show.html.erb
<h1><%=@patient.full_name%></h1>
<h3>Age: <%= @patient.age %>
<h3>Gender: <%= @patient.gender %></h3>
<h3>Contact Information: </h3>
<h4>
<div><%= button_to "Edit Patient", edit_patient_path(@patient), method: :get %></div>
<br />
<div><%= button_to "Delete Patient", patient_path(@patient), method: :delete %></div>
</h4>
<hr />